install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - appveyor DownloadFile https://github.com/nats-io/nats-streaming-server/releases/download/v0.2.0/nats-streaming-server-windows-amd64.zip
  - 7z e https://github.com/nats-io/nats-streaming-server/releases/download/v0.2.0/nats-streaming-server-windows-amd64.zip nats-streaming-server.exe -r -oc:\projects\nss\build
  - cmd: set PATH=%PATH%;C:\projects\nss\build
before_build:
  - nuget restore
build:
  project: STAN.sln
